### ISSUE TITLE
Valencia becoming indy

### ISSUE THREAD

**Issue by Atlantispy** [Amazonys/Imperialism-Reinvigorated#40]
Latest unstable build, Valencia still becoming independent (didn't see method, will check later if it was pretender rebels)

**Comment by Amazonys** [comment]
I have heard reports of this, but have yet to see why. I think it might have something to do with Castile going over relationship limit with the PU of Aragon in Iberian Wedding. Making that the event the one that integrates the subkingdoms for now...

**Comment by Amazonys** [comment]
Also made it impossible to get rid of a French principality or Iberian reino country that is in PU through the abandon PU diplo action

**Comment by Pbhuh** [comment]
Yeah i've looked into it myself. I cant seem to pinpoint it down but it really seems based on weird mechanics because it only happens to valencia and sometimes sicily and not catalonia. Not sure how we can fix this. Maybe government rank ? Either we can i guess just get a workarround working where in the succession it also Unions valencia and sicily inherently so it always happens.

**Comment by Atlantispy** [comment]
Does Aragon and Castile not have -liberty desire? We could reduce it by making Sicily, Naples and Balaeres into Domains?

**Comment by Amazonys** [comment]
The diplo action to abandon PUs should now be invalid if the nation in question is a cokingdom as defined by their government reform

**Comment by Pbhuh** [comment]
Perhaps we need to shift the PU's to dominions when the castillian event happens so taht castille only has PU's over Leon, Aragon and maybe sicily/naples.

**Comment by Amazonys** [comment]
Maybe Iberian Wedding makes Mallorcas, Sardinia, Sicily all domains?

**Comment by Atlantispy** [comment]
As long as the War of the Communeros then integrates those domains that should work
